name: SUJIN KANG
title: "'s HDD"
description: Hi
tags:
  - Awarded
  - Node.js
  - HTML/CSS
  - C++
  - Backend
  - JavaScript
  - Python
  - Data-Structure
  - Docker
  - Leadership
  - Award
  - SSLAB
  - Book
  - express
  - vue
  - PM
  - UX/UI
  - Launching
  - CloudFoundry

show_hero: true
menu:
  - title: FEATURED
    url: /category/featured
  - title: PROJECT
    url: /category/project
  - title: LIBRARY
    url: /category/library
  - title: RESEARCH
    url: /category/research
  - title: ACTIVITY
    url: /category/activity
email: waterjin326@gmail.com
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id:
